---
title: "main_memory"
author: "Huijun Cui"
date: "April 8, 2018"
output: html_document
---
```{R}
rm(list=ls())
```
```{r setup, include=FALSE}
setwd("../lib")
source("functions.R")
```
```{r}
load("../data/movie_train.RData")
load("../data/movie_test.RData")
load("../data/MS_train.RData")
load("../data/MS_test.RData")
```
## similarity weights
### Calculate pearson correlation
```{r}
weight_pearson_MS_train <- calc_weight(MS_UI, method = 'pearson')
save(weight_pearson_MS_train, file = 'weight_pearson_MS_train.RData')

weight_pearson_movie_train <- calc_weight(movie_UI, method = 'pearson')
save(weight_pearson_movie_train, file = 'weight_pearson_movie_train.RData')
```
### Calculate spearman correlation
```{r}
weight_spearman_MS_train <- calc_weight(MS_UI, method = 'spearman')
save(weight_spearman_MS_train, file = 'weight_spearman_MS_train.RData')

weight_spearman_movie_train <- calc_weight(movie_UI, method = 'spearman')
save(weight_spearman_movie_train, file = 'weight_spearman_movie_train.RData')
```
### Calculate cosine correlation
```{r}
weight_cosine_MS_train <- calc_weight(MS_UI, method = 'cosine')
save(weight_cosine_MS_train, file = 'weight_cosine_MS_train.RData')

weight_cosine_movie_train <- calc_weight(movie_UI, method = 'cosine')
save(weight_cosine_movie_train, file = 'weight_cosine_movie_train.RData')
```
### Calculate entropy correlation
```{r}
weight_entropy_MS_train <- calc_weight(MS_UI, method = 'entropy')
save(weight_entropy_MS_train, file = 'weight_entropy_MS_train.RData')

weight_entropy_movie_train <- calc_weight(movie_UI, method = 'entropy')
save(weight_entropy_movie_train, file = 'weight_entropy_movie_train.RData')
```
### Calculate mean-square difference correlation
```{r}
weight_msd_MS_train <- calc_weight(MS_UI, method = 'msd')
save(weight_msd_MS_train, file = 'weight_msd_MS_train.RData')

weight_msd_movie_train <- calc_weight(movie_UI, method = 'msd')
save(weight_msd_movie_train, file = 'weight_msd_movie_train.RData')
```
